[package]
name = "bft-testbed"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { version = "1.0.97", features = ["backtrace"] }
bincode = "2.0.1"
futures = { version = "0.3.31", default-features = false, features = ["std"] }
hdrhistogram = "7.5.4"
quinn = "0.11.7"
rand = "0.9.0"
secp256k1 = "0.30.0"
sha2 = "0.10.8"
threshold_crypto = "0.4.0"
tokio = { version = "1.44.1", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

[dev-dependencies]
rcgen = "0.13.2"
test-log = { version = "0.2.17", features = ["trace"] }

[profile.release]
debug = true
