num_replica                 4
num_faulty                  1

supply_size                 10
refill_threshold            10

# open_loop                   true
# num_max_concurrent          100
# sending_rate                2000. # request/second

# note: at least 4 (close loop) clients to fill the pipeline i.e. no "bubble" blocks
# if open loop is enabled just ensure sending rate is sufficiently frequent
num_client                  10
client_duration             10. # second
tick_interval               1. # second
server_interconnect_delay   10. # second, a rather long delay for human operation