# use_tcp                     true
num_client                  10
client_duration             10. # second
num_max_concurrent          1
tick_interval               1. # second
server_interconnect_delay   10. # second, a rather long delay for human operation