tick_interval               1. # second
num_client                  1
client_duration             10
replica_connect_delay       10. # second, a rather long delay for human operation
replica_external_address    127.0.0.1:60000
replica_external_address    127.0.0.1:60001
replica_external_address    127.0.0.1:60002
replica_external_address    127.0.0.1:60003
replica_internal_address    127.0.0.1:8000
replica_internal_address    127.0.0.1:8001
replica_internal_address    127.0.0.1:8002
replica_internal_address    127.0.0.1:8003