# spec
num_replica                 4
num_fault                  1

# replica
max_batch_size              1000

# client
# NOT supported by pbft
# open_loop                   true
# num_max_inflight            1000
# sending_rate                1000.

# task
num_client                  10
client_duration             10. # second
tick_interval               1. # second
server_interconnect_delay   0. # second, QUIC allow connect before listen so no need

## pbft
# replica
max_num_inflight            1
# task
# use_tcp                     true
# server_interconnect_delay   10. # second, rather long for human reaction

## hotstuff
# replica
supply_size                 100
refill_threshold            100

## bigbft
# client
num_concurrent              1
# task
num_shard                   16
num_stripe_shard            8
num_fast_replica            1