workload.duration       10.
workload.close-loop     true
workload.concurrency    1

open-loop.target-tput  1000

client.timeout          1.

protocol                unsharded
replication-protocol    unreplicated  

big.storage-mode        sharded
big.num-node            4
big.num-shard           100
big.num-active-copy     1
