workload.duration       10.
workload.close-loop     true
workload.concurrency    1

open-loop.target-tput   1000

client.timeout          1.

protocol                unsharded
replication-protocol    unreplicated

big.num-node            4
big.num-faulty-node     1
big.num-active-copy     1
big.num-stripe          1000
big.bypass-vote         true
big.full-storage        false

big.replay-duration     60

ycsb.get-ratio      0.
ycsb.num-key        10000000
ycsb.value-size     1000
